ALTER TABLE bikes ADD COLUMN front_brake VARCHAR(50) DEFAULT NULL;
ALTER TABLE bikes ADD COLUMN rear_brake VARCHAR(50) DEFAULT NULL;
ALTER TABLE bikes ADD COLUMN abs_type VARCHAR(50) DEFAULT NULL;
ALTER TABLE bikes ADD COLUMN wheel_type VARCHAR(50) DEFAULT NULL;
