ALTER TABLE customers 
ADD COLUMN status VARCHAR(20) DEFAULT 'active',
ADD COLUMN email_verified INT DEFAULT 0,
ADD COLUMN email_verified_at DATETIME DEFAULT NULL,
ADD COLUMN is_profile_completed INT DEFAULT 0,
ADD COLUMN otp VARCHAR(10) DEFAULT NULL,
ADD COLUMN otp_expiry DATETIME DEFAULT NULL;
